name: CI

on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [ 'macos-latest' ]
    runs-on: ${{ matrix.os }}
    env:
      BUILDLESS_APIKEY: ${{ secrets.BUILDLESS_APIKEY }}

    steps:
      - uses: actions/checkout@v3

      - name: "Setup: Buildless"
        uses: buildless/setup@v1.0.2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: |
            11
            17
          distribution: 'temurin'
          cache: gradle

      - name: Checkout Gradle Build Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Project
        run: ./gradlew ktlintCheck test compileReleaseSources
