name: CI

on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [ 'macos-latest' ]
    runs-on: ${{ matrix.os }}
    env:
      BUILDLESS_APIKEY: ${{ secrets.BUILDLESS_APIKEY }}

    steps:
      - uses: actions/checkout@v3

      - name: "Setup: Buildless"
        uses: buildless/setup@v1.0.2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: |
            11
            17
          distribution: 'temurin'
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.1.0

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.1.0

      - name: Build Project
        run: ./gradlew build
